backend:
  name: git-gateway #github
  repo: popliresourcegroup/popliresourcegroup.github.io
  branch: master # Branch to update (optional; defaults to master)
  api_root: https://api.github.com
  site_domain: popliresources.com
  base_url: https://api.netlify.com
  auth_endpoint: auth
media_folder: "uploads"
