---
label: Product List
hide_body: false
fields:
- name: productname
  type: text
  config:
    required: true
  label: ProductName
- name: thumbnail
  type: file
  config:
    maxSize: 64
  label: Thumbnail
- name: detailpictures
  type: image_gallery
  config: {}
  label: DetailPictures
- name: category
  type: select
  default: []
  config:
    required: false
    options:
    - Crawler Cranes
    - Mobile Cranes
    - Piling Equipment
    - Excavators
    - Ships/Barges
    - Others
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
- name: sold
  type: boolean
  label: Sold
  default: false
- name: layout
  type: text
  config:
    required: false
  label: layout
  hidden: true
  default: product
- name: year
  type: text
  config:
    required: false
  label: Year
- name: hours
  type: text
  config:
    required: false
  label: Hours
- name: serial_no
  type: text
  config:
    required: false
  label: Serial No.
- name: model
  type: text
  config:
    required: false
  label: Model
pages:
- product_list/CAT 320.md
- product_list/CAT320D.md
- product_list/d85EX-15.md
