---
label: Product List
hide_body: false
fields:
- name: productname
  type: text
  config:
    required: true
  label: ProductName
- name: productdescription
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: ProductDescription
- name: thumbnail
  type: file
  config:
    maxSize: 64
  label: Thumbnail
- name: detailpictures
  type: image_gallery
  config: {}
  label: DetailPictures
- name: category
  type: select
  default: []
  config:
    required: false
    options:
    - Crawler Cranes
    - Mobile Cranes
    - Piling Equipment
    - Excavators
    - Ships/Barges
    - Others
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
- name: sold
  type: boolean
  label: Sold
  default: false
